[package]
name = "private_does_not_revert"
type = "contract"
authors = [""]
compiler_version = ">=0.32.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.47.1", directory = "noir-projects/aztec-nr/aztec" }
authwit = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.47.1", directory = "noir-projects/aztec-nr/authwit" }
compressed_string = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.47.1", directory = "noir-projects/aztec-nr/compressed-string" }